esphome:
  name: dozownik-akwarium
  friendly_name: Dozownik Akwarium

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Pobieranie danych z pliku secrets.yaml
wifi:
  ssid: "MacKuz_20"
  password: "qazxswedcvfrt"
  power_save_mode: NONE 
  fast_connect: true   # Przyspiesza łączenie
  #output_power: 18.5dB # Czasami obniżenie mocy pomaga przy bliskim kontakcie z routerem
  # Dodaj to poniżej:
  reboot_timeout: 0s # Zapobiega restartom przy braku wifi
  # Opcjonalnie: ustawienie statycznego IP przyspiesza łączenie
  # manual_ip:
  #   static_ip: 192.168.1.50
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
on_connect:
    - logger.log: "WiFi jest gotowe!"

# Umożliwia wgrywanie kodu przez WiFi
ota:
  - platform: esphome
    password: !secret ota_password

# Panel WWW dostępny pod adresem IP urządzenia
web_server:
  port: 80

# Natywne połączenie z Home Assistant
api:
  encryption:
    key: !secret api_encryption_key

# Logi przydatne przy debugowaniu (widoczne w terminalu)
logger:
  level: DEBUG

i2c:
  sda: GPIO4
  scl: GPIO3
  scan: true  # Dzięki temu w logach zobaczysz adres 0x68


# Magistrala SPI dla wyświetlacza
spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11

# Konfiguracja wyświetlacza TFT 2.4 cala (ILI9341)
display:
  - platform: ili9xxx
    model: ILI9341
    id: my_tft
    invert_colors: false  # Dodaj tę linię
    cs_pin: GPIO10
    dc_pin: GPIO9
    reset_pin: GPIO8
    rotation: 90
    lambda: |-
      // Czyścimy ekran na czarno
      it.fill(id(COLOR_BLACK));
      
      // Rysujemy ramkę nagłówka
      it.rectangle(0, 0, 320, 32, id(COLOR_GRAY));
      
      // Tekst powitalny
      it.print(160, 10, id(font_medium), id(COLOR_WHITE), TextAlign::TOP_CENTER, "DOZOWNIK 300L");
      
      // Status systemu
      it.print(160, 120, id(font_small), id(COLOR_GREEN), TextAlign::CENTER, "System Online - Czekam na dane...");
      
      // Linia oddzielająca stopkę
      it.line(0, 210, 320, 210, id(COLOR_GRAY));

# Definicja czcionek (ESPHome sam je pobierze z Google Fonts)
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 14
  - file: "gfonts://Roboto"
    id: font_medium
    size: 20

# Paleta kolorów używana w projekcie
color:
  - id: COLOR_BLACK
    red: 0%
    green: 0%
    blue: 0%
  - id: COLOR_WHITE
    red: 100%
    green: 100%
    blue: 100%
  - id: COLOR_GREEN
    red: 0%
    green: 100%
    blue: 0%
  - id: COLOR_GRAY
    red: 30%
    green: 30%
    blue: 30%
  - id: COLOR_YELLOW
    red: 100%
    green: 100%
    blue: 0%